### ISSUE TITLE
用手滑动的时候，底部的菜单没有变化，当开启动画的时候，滑动到最边缘的时候。

### ISSUE THREAD

**Issue by choubaguai** [ittianyu/BottomNavigationViewEx#1]
用手滑动的时候，底部的菜单没有变化，当开启动画的时候，滑动到最边缘的时候。
我开启了所有动画，然后，滑动viewpager，当到最边缘的时候，并不能将菜单缩小到相应的位置。

**Comment by ittianyu** [comment]
没明白你的意思，手动滑动的是`ViewPager`还是什么？如果是`ViewPager`，你可以下载整个工程，里面配合`ViewPager`的例子。如果是其他的控件，你需要在滑动的时候，调用底部导航条的 `setCurrentItem`来设置当前选中的位置。
滑倒边缘时，默认ViewPager是不能循环滑动的，如果要，你可以查找相关资料，有实现ViewPager无限循环滑动的方法。
如果菜单数>3，默认是开启了所有动画的;小于等于3，则只有shiftingMode和itemShiftingMode没开启。
本库只是用反射对官方的库进行了方法的扩展，并没有直接修改官方库里面的代码哦。

如果上述说明无法帮你解决问题，你可以联系我QQ 86839868 或者 微信 ittianyu，记得把截图发出来，容易明白你的意思。

**Comment by ittianyu** [comment]
如果没有其他疑问，我就先关闭这个问题了。感谢您的反馈。
