### ISSUE TITLE
Problem with badges in fragment

### ISSUE THREAD

**Issue by venkataramanab** [ittianyu/BottomNavigationViewEx#10]
it looks like this and I'm figured that action bar height is returning 0.
![device-2017-03-04-131340](https://cloud.githubusercontent.com/assets/15572489/23577080/7d1a1cb8-00dc-11e7-9c7f-24c215b4fd74.png)

**Comment by ittianyu** [comment]
You could see the [demo](https://github.com/ittianyu/BottomNavigationViewEx/blob/master/app/src/main/java/com/ittianyu/bottomnavigationviewexsample/features/badgeview/BadgeViewActivity.java). The position need calculate.

**Comment by venkataramanab** [comment]
I saw the same, but `actionBarHeight = actionBar.getHeight();` returns zero.

**Comment by ittianyu** [comment]
That may be the view haven't load. So you need run it in view.post(runnable).

**Comment by venkataramanab** [comment]
Yeah!! this worked. Thanks.

**Comment by ittianyu** [comment]
You are welcome.
