### ISSUE TITLE
Placing FloatingActionButton in front BottomNavigationViewEx

### ISSUE THREAD

**Issue by kaajalgupta** [ittianyu/BottomNavigationViewEx#100]
I was seeing your library, and couldn't understand how to place the floating action button in front of the bottomnavigationviewex in a coordinator layout. Can you tell me how?

**Comment by syarkhan** [comment]
1. In your menu layout, add an item with empty title --> 
<item
        android:id="@+id/i_empty"
        android:title="" />
2. Place your fab in the same layout where BottomNavigationViewEx widget is --> 
<android.support.design.widget.FloatingActionButton
        android:id="@+id/fabPostNews"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="16dp"
        android:src="@drawable/post_icon_2"
        app:backgroundTint="#840f73"
        app:borderWidth="0dp"
        app:elevation="9dp" />

    <com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx
        android:id="@+id/my_toolbar_bottom"
        android:layout_width="match_parent"
        android:layout_height="45dp"
        android:layout_alignParentBottom="true"
        android:background="@drawable/nav_border_bottom"
        app:menu="@menu/botton_navigation_main"/>

3. Result-->
![image](https://user-images.githubusercontent.com/19317415/42728088-eb8f3436-87cb-11e8-84e5-07f942440cf0.png)

**Comment by ArleyPereira** [comment]
the part of the button that is outside the bar is not clickable, is there any alternative to work
