### ISSUE TITLE
键盘弹出问题

### ISSUE THREAD

**Issue by yishangfei** [ittianyu/BottomNavigationViewEx#106]
想问一下 如果使用fragment 嵌套fragment  写edittext  会导致键盘弹出上面会有BottomNavigationView

![image](https://user-images.githubusercontent.com/15099278/42806597-630e369e-89e1-11e8-8294-c9a1d7da44cb.png)

**Comment by ittianyu** [comment]
参考
https://blog.csdn.net/junhuahouse/article/details/78237932

**Comment by yishangfei** [comment]
老哥  我参考这个去实现  发现和我的有些出入呀  首先会导致BottomNavigationView文字不见  还有他的那个rootview不是activity的 因为我这边监听activity父控件监听这个事件是没有值是无法变动的   而在在edittext 所在的fragment监听会导致整个错乱

**Comment by yishangfei** [comment]
getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN);
