### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by DhruvUpadhyaya** [ittianyu/BottomNavigationViewEx#108]
I'm getting crash after implemeting i.e after disabling the animation and other shifting stuff
        bottomNavigationView.enableItemShiftingMode(false);
        bottomNavigationView.enableAnimation(false);

**Comment by bimsina** [comment]
same here can anyone solve this problem. Here is the full problem.
https://stackoverflow.com/questions/51618340/bottomnavigationviewex-null-pointer-exception

**Comment by btow** [comment]
It is possible that this solution is suitable for disabling the animation, but not for disabling the shift mode.

**Comment by fairytale110** [comment]
@DhruvUpadhyaya @bimsina Fixed in #118

**Comment by ubuntudroid** [comment]
You can as well use the fix on our fork:

```
implementation 'com.github.stanwood:BottomNavigationViewEx:41e335d'
```

**Comment by ittianyu** [comment]
I am sorry to be late. Please use version 2.0.0 if support lib >= 28. 
Version 27 is abandoned.
For AndroidX, please add config into `gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```
