### ISSUE TITLE
Unable to add badge view like in sample app

### ISSUE THREAD

**Issue by ykorshev** [ittianyu/BottomNavigationViewEx#109]
I m trying to add badge to BottomNavigationItemView, but QBadgeView always throws exception that parent view is null. After debug session, i have discovered that BottomNavigationItemView parent is really null. What i am doing wrong?

**Comment by fairytale110** [comment]
Fixed in #118

**Comment by ittianyu** [comment]
Please try new version.
Using version 2.0.0 if support lib >= 28.
