### ISSUE TITLE
一直有波浪线

### ISSUE THREAD

**Issue by Lans** [ittianyu/BottomNavigationViewEx#11]

**Comment by Lans** [comment]
mMenuView.updateMenuView();
updateMenuView一直有波浪线

**Comment by ittianyu** [comment]
波浪线是什么意思 ？ 有截图吗

**Comment by Lans** [comment]
发自网易邮箱大师
            在2017年03月05日 19:31，ittianyu 写道： 波浪线是什么意思 ？ 有截图吗

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ittianyu/BottomNavigationViewEx","title":"ittianyu/BottomNavigationViewEx","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ittianyu/BottomNavigationViewEx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ittianyu in #11: 波浪线是什么意思 ？ 有截图吗"}],"action":{"name":"View Issue","url":"https://github.com/ittianyu/BottomNavigationViewEx/issues/11#issuecomment-284221851"}}}

**Comment by ittianyu** [comment]
什么鬼
