### ISSUE TITLE
多次点击字体不显示bug

### ISSUE THREAD

**Issue by leifu1107** [ittianyu/BottomNavigationViewEx#113]
多次点击字体不显示bug多次点击字体不显示bug多次点击字体不显示bug,建议修复

**Comment by Longalei** [comment]
就不能贴个图或者描述详细点嘛？要不然提这个Issues有意义？ @leifu1107

**Comment by leifu1107** [comment]
现实比较难模拟,只是偶尔会出现这个bug, enableShiftingMode(false);enableItemShiftingMode(false);底部有三个导航按钮,连续第一个和最后一个按钮多次点击,再点中间一个,有时候会出现其中一个字体不显示,不快速点击切换页面是没问题的

**Comment by ittianyu** [comment]
试试升级 2.0.0 和 supprot 28.0.0
