### ISSUE TITLE
not syncing

### ISSUE THREAD

**Issue by Reach-Horizon** [ittianyu/BottomNavigationViewEx#115]
unable to sync gradle after adding the dependency.......
Error Message showing->Failed to resolve: com.github.ittianyu:BottomNavigationViewEx:1.2.4..

**Comment by fairytale110** [comment]
It just a java file，Manual is better

**Comment by ittianyu** [comment]
Step 1. Add it in your root build.gradle at the end of repositories:
```groovy
allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
		maven { url "https://maven.google.com" }
	}
}
```
