### ISSUE TITLE
Crashes on 28 api

### ISSUE THREAD

**Issue by freaksgit** [ittianyu/BottomNavigationViewEx#116]
` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.getBottomNavigationItemViews(BottomNavigationViewEx.java:569)
        at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.enableItemShiftingMode(BottomNavigationViewEx.java:430)`

**Comment by fairytale110** [comment]
see my issues #118

**Comment by admark1986** [comment]
I am getting same error.

**Comment by ddveloperr** [comment]
Same here.

**Comment by Tripwire999** [comment]
same here!

**Comment by ubuntudroid** [comment]
You can use the fix on our fork:

```
implementation 'com.github.stanwood:BottomNavigationViewEx:41e335d'
```

**Comment by ittianyu** [comment]
I am sorry to be late. Please use version 2.0.0 if support lib >= 28. 
Version 27 is abandoned.
For AndroidX, please add config into `gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```
