### ISSUE TITLE
在API 28 setShiftingMode 方法不存在

### ISSUE THREAD

**Issue by fairytale110** [ittianyu/BottomNavigationViewEx#117]
compileSdkVersion  : 28
getBottomNavigationItemView(position).setShiftingMode(enable); 无效。setShiftingMode不存在了。
但是如果我的项目必须要API28或者今后更高版本，同时又需要ShiftingMode，我该如何使用BottomNavigationViewEx呢？

**Comment by fairytale110** [comment]
我自己解决了，谢谢

**Comment by carozhu** [comment]
怎么解决的。大佬
