### ISSUE TITLE
mMenuView.getClass() 报空指针

### ISSUE THREAD

**Issue by fairytale110** [ittianyu/BottomNavigationViewEx#118]
` 
 BottomNavigationMenuView mMenuView = getBottomNavigationMenuView();
`
得到的mMenuView 是空的
compileSdkVersion  : 28,
请教怎么解决这个问题，如果必须使用API 25以上，毕竟以后会有新特性。

**Comment by fairytale110** [comment]
已解决，你的代码没适配API 28，

//你的代码：        mButtons = getField(mMenuView.getClass(), mMenuView, "mButtons");
   我改后的：     mButtons = getField(mMenuView.getClass(), mMenuView, "buttons");

如此类似的问题很多，getField(Class targetClass, Object instance, String fieldName) 
中的fieldName 很多在API 28 改变了。希望对作者有帮助，最好判断下API版本做适配。

**Comment by truongnmt** [comment]
How can I edit the library source code. I can open it but Android Studio said that the file is read-only :/

**Comment by AstonBraham** [comment]
Can somebody please translate this to English ?
I'm stuck and can't understand @fairytale110 's solution.

**Comment by fairytale110** [comment]
@AstonBraham take a look at  [HERE](https://github.com/ittianyu/BottomNavigationViewEx/issues/110#issuecomment-415265565)

**Comment by truongnmt** [comment]
@AstonBraham  
fairytale110 explained it. You get the source code, then File -> New -> New Module
Then find it `BottomNavigationViewEx.java` class, change `mButtons` to `buttons`: 

```
mButtons = getField(mMenuView.getClass(), mMenuView, "buttons");
```

**Comment by millerovv** [comment]
@fairytale110 Hi! Will you try to update your library with a fix of this issue, so we wouldn't need to pull all of the source code manually?

**Comment by fairytale110** [comment]
@millerovv some one have pulled a same request ，but it was closed，you can find it

**Comment by admark1986** [comment]
@fairytale110 Hi, I have done what you mentioned here but still i am getting this error. Any solution for this?

**Comment by ubuntudroid** [comment]
You can simply use the fix on our fork:

```
implementation 'com.github.stanwood:BottomNavigationViewEx:41e335d'
```

**Comment by zachdev** [comment]
> You can simply use the fix on our fork:
> 
> ```
> implementation 'com.github.stanwood:BottomNavigationViewEx:41e335d'
> ```

`bottomNavigationView.setTextVisibility(true);` doesn't seem to be working on this fork.

**Comment by zachdev** [comment]
> You can simply use the fix on our fork:
> 
> ```
> implementation 'com.github.stanwood:BottomNavigationViewEx:41e335d'
> ```

`bottomNavigationView.setTextVisibility(true);` doesn't currently seem to be working on this fork, unfortunately.

**Comment by ubuntudroid** [comment]
@zachdev will check that later today.

**Comment by ubuntudroid** [comment]
@zachdev just tested, works perfectly fine for me. What isn't working for you exactly? Guess this is not connected to the changes on our fork.
