### ISSUE TITLE
Different behavior on real phone VS emulator 

### ISSUE THREAD

**Issue by foxalone** [ittianyu/BottomNavigationViewEx#121]
My question is - the bottom view behavior in an emulator and in the real phone is really different. I've even checked with two different phones: Huawei p8 and galaxy s7 with different android version but still the behavior in the phone is the same but different from behavior in the emulator

please help

**Comment by stephyswe** [comment]
How you even get this to work? My Huawei p8 just closes the App directly, it uses API 23. 

But emulated phones on higher API works fine. :(

**Comment by foxalone** [comment]
Actually, my API is 21 , lol

**Comment by ittianyu** [comment]
Any screenshot?

**Comment by foxalone** [comment]
It's just different behavior  - no need for screenshot
