### ISSUE TITLE
每次运行都报这个警告，但是不影响。

### ISSUE THREAD

**Issue by qiaoguoqiang** [ittianyu/BottomNavigationViewEx#123]
第一次运行的时候，报了这个错误，但是不影响app使用，不知道这个因为啥？

W/System.err: java.lang.NoSuchFieldException: No field mAnimationHelper in class Landroid/support/design/internal/BottomNavigationMenuView; (declaration of 'android.support.design.internal.BottomNavigationMenuView' appears in /data/app/com.bandaorongmeiti.news-K4Th0fIJWlhfexLjzykytg==/base.apk)

**Comment by ittianyu** [comment]
可以试试 升级 28.0.0，和 2.0.0 版本
