### ISSUE TITLE
和support version28.0.0不兼容

### ISSUE THREAD

**Issue by LambdaV5** [ittianyu/BottomNavigationViewEx#125]
和support version28.0.0不兼容,出现npe

**Comment by juanjecilla** [comment]
There is a class duplicate when updating to 28.0.0.

**Comment by limuyang2** [comment]
[](https://github.com/ittianyu/BottomNavigationViewEx/issues/126)
这里已解决

**Comment by limuyang2** [comment]
[126](https://github.com/ittianyu/BottomNavigationViewEx/issues/126)

**Comment by ittianyu** [comment]
I am sorry to be late. Please use version 2.0.0 if support lib >= 28. 
Version 27 is abandoned.
For AndroidX, please add config into `gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```
