### ISSUE TITLE
Setting icon from URL (Glide)

### ISSUE THREAD

**Issue by lucandr** [ittianyu/BottomNavigationViewEx#130]
Hi, I need to show on an icon a profile picture that is coming from an URL.

Do you know how can I achive this?

I have already tried the following:

1- I tried setOnNavigationItemSelectedListener, but it is now working in my code. I am using Navigation library from arch components and when I press the button nothing happens, the navigation breaks. 

````
binding.bottomNavigationView.setOnNavigationItemSelectedListener(new BottomNavigationView.OnNavigationItemSelectedListener() {
            @Override
            public boolean onNavigationItemSelected(@NonNull MenuItem item) {
                return false;
            }
        });
````

2- I tried to set a selector when I receive the drawable from Glide, but it isn't working, it shows the first time but when I click it, it dissapears.
````
Glide
                .with(this)
                .load("url")
                .into(new SimpleTarget<Drawable>() {
                    @Override
                    public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                        StateListDrawable states = new StateListDrawable();
                        states.addState(new int[]{android.R.attr.state_pressed}, resource);
                        states.addState(new int[]{android.R.attr.state_checked}, resource);
                        states.addState(new int[]{}, resource);
                        activityHomeBinding.bottomNavigationView.getIconAt(1).setImageDrawable(states);
                    }
                });
````

Any ideas?

Thanks

**Comment by lucandr** [comment]
I made it.

**Comment by Cr321** [comment]
> I made it.

Hi, how did you  make it?

**Comment by lucasgriotto** [comment]
@Cr321, you can do it like this:

```
Glide
            .with(this)
            .load(pictureUrl)
            .apply(RequestOptions().circleCrop())
            .into(object : CustomTarget<Drawable>() {

                override fun onLoadCleared(placeholder: Drawable?) {
                }

                override fun onResourceReady(
                    resource: Drawable,
                    transition: Transition<in Drawable>?
                ) {
                    val states = StateListDrawable()
                    states.addState(intArrayOf(android.R.attr.state_pressed), resource)
                    states.addState(intArrayOf(android.R.attr.state_checked), resource)
                    states.addState(intArrayOf(), resource)
                    val menu = bottom_nav_view.menu
                    val te = menu.findItem(R.id.menu_item_profile)
                    te.icon = states
                }
            })
```

**Comment by Cr321** [comment]
> @Cr321, you can do it like this:
> 
> ```
> Glide
>             .with(this)
>             .load(pictureUrl)
>             .apply(RequestOptions().circleCrop())
>             .into(object : CustomTarget<Drawable>() {
> 
>                 override fun onLoadCleared(placeholder: Drawable?) {
>                 }
> 
>                 override fun onResourceReady(
>                     resource: Drawable,
>                     transition: Transition<in Drawable>?
>                 ) {
>                     val states = StateListDrawable()
>                     states.addState(intArrayOf(android.R.attr.state_pressed), resource)
>                     states.addState(intArrayOf(android.R.attr.state_checked), resource)
>                     states.addState(intArrayOf(), resource)
>                     val menu = bottom_nav_view.menu
>                     val te = menu.findItem(R.id.menu_item_profile)
>                     te.icon = states
>                 }
>             })
> ```

ok, thx

**Comment by Phues** [comment]
what is the version for this code in java please?
