### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by dongyanming** [ittianyu/BottomNavigationViewEx#139]
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    **implementation 'com.github.ittianyu:BottomNavigationViewEx:2.0.2'**
    // leakcanary  
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.5.4'
    releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'
    testImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'
    implementation 'q.rorbin:badgeview:1.1.0'
}

**只要添加implementation 'com.github.ittianyu:BottomNavigationViewEx:2.0.2' 这一句就报以下错误，请问是怎么回事啊？？**

`Android resource linking failed
Output:  F:\Android\DemoTest1\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
F:\Android\DemoTest1\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
F:\Android\DemoTest1\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1279: error: resource android:attr/fontVariationSettings not found.
F:\Android\DemoTest1\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1280: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: C:\Users\dong\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\57fca2fd2cc274def0a7c1ac25fa0f14\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        C:\Users\dong\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
        --manifest\
        F:\Android\DemoTest1\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        F:\Android\DemoTest1\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @F:\Android\DemoTest1\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        F:\Android\DemoTest1\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --custom-package\
        com.example.dong.demotest1\
        -0\
        apk\
        --preferred-density\
        420dpi\
        --output-text-symbols\
        F:\Android\DemoTest1\app\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
`

**Comment by mingxin-yang** [comment]
@dongyanming 请问你是如何解决的

**Comment by dongyanming** [comment]
> @dongyanming 请问你是如何解决的
当初没看文档，是版本问题，你看一下首页有说明文档

**Comment by dongyanming** [comment]
@mingxin-yang 
我当初没看文档，你在这个首页有说明文档，是版本问题
