### ISSUE TITLE
api v19 null pointer exception

### ISSUE THREAD

**Issue by olegsvs** [ittianyu/BottomNavigationViewEx#140]
Hi, i have error:
```
java.lang.NullPointerException
        at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.getBottomNavigationItemViews(BottomNavigationViewEx.java:569)
        at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.setTextVisibility(BottomNavigationViewEx.java:244)
```

inject:
```
    @BindView(R.id.fr_main_bottom_nav)
    BottomNavigationViewEx bottomNav;
```

And any method from BottomNavigationEx return null pointer, for example 
`bottomNav.setTextVisibility(false);`

**Comment by ittianyu** [comment]
Please check you lib version and choose one.

1. old version support lib is 25 or 26
```
compile 'com.github.ittianyu:BottomNavigationViewEx:1.2.4'
compile "com.android.support:design:26.+"
```
2. new version support lib = 28
```
implementation 'com.github.ittianyu:BottomNavigationViewEx:2.0.2'
implementation "com.android.support:design:28.0.0"
```
3. AndroidX use new version，and add config into gradle.properties
```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by olegsvs** [comment]
@ittianyu, thx you, i used 28 support lib and old version BottomNavigationViewEx. Thx for awesome lib and fast answer)

**Comment by Benvanj** [comment]
good day, ittianyu

I have a similiar problem and have found your solutions posted all over the web... but even after I follow your solutions I have problems... could you please assist? or are you supporting the library..
Thanks:
error:
java.lang.NullPointerException: Attempt to invoke virtual method 'com.ittianyu.bottomnavigationviewex.BottomNavigationViewInner com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.enableAnimation(boolean)' on a null object reference...
