### ISSUE TITLE
android:allowBackup conflict

### ISSUE THREAD

**Issue by fthdgn** [ittianyu/BottomNavigationViewEx#15]
The manifest of this library sets allowBackup to true. This value may conflict with the manifest of app. I think this line can be deleted from the manifest of the library because it is not required.

Error log:
```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:10:9-36
	is also present at [com.github.ittianyu:BottomNavigationViewEx:1.1.3] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:8:5-28:19 to override.
```

Code location:
https://github.com/ittianyu/BottomNavigationViewEx/blob/master/widget/src/main/AndroidManifest.xml#L4

**Comment by ittianyu** [comment]
I'm sorry for not replying in time. I had delete it. You could update your lib version to 1.1.4. 
Thanks for your feedback.

**Comment by fthdgn** [comment]
Thank you for update and the library.
