### ISSUE TITLE
crashed on enableAnimation()

### ISSUE THREAD

**Issue by SaadBilal** [ittianyu/BottomNavigationViewEx#154]
I am using 2.0.0 but it is crashing when called enableAnimation(), I have also change the methods enableShiftmode and enableItemShiftMode

```
activityMainViewBinding.bottomNavigation.setLabelVisibilityMode(1); // for enableShiftingMode(false)
    activityMainViewBinding.bottomNavigation.setItemHorizontalTranslationEnabled(false);// for enableItemShiftingMode(false)

//    activityMainViewBinding.bottomNavigation.enableShiftingMode(false);
//    activityMainViewBinding.bottomNavigation.enableItemShiftingMode(false);
```

Please advice how to resolve this animation issue, also unable to set custom type font. Also crashing when setting custom fonts. Any help ?

**Comment by yalematta** [comment]
I have the same problem. Any idea on how to prevent that from happening?

**Comment by ittianyu** [comment]
What is the version of support lib ? Now is only support `28.0.0`.

**Comment by ittianyu** [comment]
@yalematta Any detail ? Can you reproduce every time? If so, may be you use a uncompatible version of support lib. If only happen on some phone or when public release apk . You can try the new version `2.0.4`.
