### ISSUE TITLE
AndroidX不能正常使用

### ISSUE THREAD

**Issue by LaoXiZi** [ittianyu/BottomNavigationViewEx#156]
![2019-02-15_182951](https://user-images.githubusercontent.com/23638133/52850926-be83d900-314f-11e9-8819-4394b47e1370.png)

**Comment by LaoXiZi** [comment]
关于AndroidX的依赖配置方式是错误的

**Comment by ittianyu** [comment]
AndroidX 是需要依赖原来的 support 库，然后在 gradle 的选项中配置支持 AndroidX
