### ISSUE TITLE
建议大佬新建一个QQ群 欢迎广大爱好者提问优化以后找个框架

### ISSUE THREAD

**Issue by xuxinjiang** [ittianyu/BottomNavigationViewEx#157]
478104175 这是我的QQ 希望大佬组件一个新群 我可以负责拉人进来  bind.bnve.enableAnimation(true);
        bind.bnve.enableShiftingMode(false);
        bind.bnve.enableItemShiftingMode(true);这三种动画分别什么什么作用？ 第一个动画跟第三个好像没什么区别 ？

**Comment by ittianyu** [comment]
qq反馈群： 913494600
