### ISSUE TITLE
如何自定义选中的图标？比如APP有两套icon的。未选中和选中都是两个不一样的，而不只是单单改变个颜色

### ISSUE THREAD

**Issue by Lsy1992** [ittianyu/BottomNavigationViewEx#159]

**Comment by Lsy1992** [comment]
额 不好意思没仔细看文档， 找到解决方法了：setIconTintList

**Comment by Lsy1992** [comment]
setIconTintList 只可以设置颜色渲染。。。

**Comment by Lsy1992** [comment]
已解决， 给后边来的小伙伴参考： https://blog.csdn.net/u014614038/article/details/79417465

**Comment by ittianyu** [comment]
版本 `2.0.4` 之后，如果 xml 里面不设置 `app:itemIconTint`，就不会再有默认的 tint。
之前官方的库里有一个默认的 tint，我已经主动清理了。如果 xml 设置了，则还是会生效的。
