### ISSUE TITLE
Drop min SDK to 9

### ISSUE THREAD

**Issue by pserwylo** [ittianyu/BottomNavigationViewEx#16]
Hi there,

I was wondering if you could elaborate on the reason for having a minSdk of 11. It seems to have been so since your initial commit, but it seems to compile/lint fine when I drop the minSdk to 9. Given the support library supports down to 9, would you consider dropping the minSdk to 9 for this library too?

Cheers.

**Comment by ittianyu** [comment]
I had update it. You could see the change in '1.1.5'. Thanks for your feedback.

**Comment by pserwylo** [comment]
Thats great @ittianyu, thank you for your fast response and for the change.
