### ISSUE TITLE
setOnNavigationItemSelectedListener点击回调无效

### ISSUE THREAD

**Issue by zhengjiong** [ittianyu/BottomNavigationViewEx#17]
support.design升级到25.3.0,会出现此问题, 25.2.0不会

**Comment by ittianyu** [comment]
感谢您反馈，我晚上回去看看。

**Comment by ittianyu** [comment]
升级到 25.3.0 后并未发现你说的问题，可否提供您的代码。

**Comment by zhengjiong** [comment]
不好意思來晚了, 找到問題原因了, 是調用方法順序的問題, SetupWithViewPagerActivity中initEvent和initData交換下位置就會出問題, 不過在25.2.0是沒這個問題的, 25.3之後的版本才有這個問題!
