### ISSUE TITLE
ERROR: Failed to resolve: com.github.ittianyu:BottomNavigationViewEx:2.0.4

### ISSUE THREAD

**Issue by cirogg** [ittianyu/BottomNavigationViewEx#174]
Hi! I used this library one year ago with no problem.

Today i wanted to use it in a new project and im having this error when y try to sync graddle:

ERROR: Failed to resolve: com.github.ittianyu:BottomNavigationViewEx:2.0.4

**Comment by Presheda** [comment]
Try to make sure you have added  `maven { url "https://jitpack.io" }` to your project's build.gradle file.
not your app module build.gradle

**Comment by cirogg** [comment]
```
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'

        // NOTE: Do not place your applicaton dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        jcenter()
        google()
    }
}
```


I have this

**Comment by Presheda** [comment]
its suppose to look like this. it's suppose to be added here

 `allprojects {

    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }        
   }
}
`
        

![Screenshot (4)](https://user-images.githubusercontent.com/26353504/64027789-5b7cf100-cb39-11e9-9136-da808e0538ce.png)

**Comment by cirogg** [comment]
Oh, thank you very much.
 
i was writting the lines inside of "buildscript>Repositories" and i had to write them like you said in the "allprojects > repositories".

Working fine now.

Thanks!

**Comment by AlexisVidal** [comment]
I am using xamarin and proguard, un the release i get this error, i already add proguard lunes about clase 
![IMG-20191104-WA0000](https://user-images.githubusercontent.com/22396974/68202723-391caf00-ff92-11e9-82cf-db2d8e8aaad7.jpg)

**Comment by nachiket-gohil** [comment]
**if you are facing this issue even after syncing gradle, then you must have to consider this case:** 

In Android studio, inside 'app' directory, open your project level build.gradle file:
_app>build.gradle (Project:abc)_

find **"allprojects{"** block, inside this block add this two new lines:

```
maven { url "https://jitpack.io" }
maven { url "https://maven.google.com" }
```

and press **Try again** in Android sytudio

**Comment by MaraBytes** [comment]
If  you can't find the "allprojects{}" section, add it in your settings,gradle
