### ISSUE TITLE
当设置了 沉浸式状态栏,bnve的高度不受控制了

### ISSUE THREAD

**Issue by zhangqifan1** [ittianyu/BottomNavigationViewEx#177]
![图片](https://user-images.githubusercontent.com/29973474/67999557-d11b4f80-fc97-11e9-9842-ef6631211f66.png)

**Comment by zhangqifan1** [comment]
求教大佬 这个怎么改

**Comment by zhangqifan1** [comment]
额,我在bnve 底下放了个view  解决了.
<View
        android:layout_alignParentBottom="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

**Comment by xluu233** [comment]
我也是高度显示不正确，老哥怎么设置的
