### ISSUE TITLE
Is it possible to change icon  when select and unselect

### ISSUE THREAD

**Issue by dhavalkba** [ittianyu/BottomNavigationViewEx#18]
I want to set different icon when i select menu and also in unselect icon

**Comment by ittianyu** [comment]
Yeah. I have add it. Please pull the last code.

![](https://github.com/ittianyu/BottomNavigationViewEx/blob/1.1.7/read_me_images/icon_selector_1.jpg?raw=true)
![](https://github.com/ittianyu/BottomNavigationViewEx/blob/1.1.7/read_me_images/icon_selector_2.jpg?raw=true)
