### ISSUE TITLE
Custom typeface only works for the selected item

### ISSUE THREAD

**Issue by janakaj** [ittianyu/BottomNavigationViewEx#19]
Really cool extensions for BottomNavigationView. I'm having an issue with setting a custom font.

I'm using the following code:

    Typeface typeface = Typeface.createFromAsset(getAssets(), "fonts/SourceSansPro/SourceSansPro-Bold.ttf");
    bnve.setTypeface(typeface);

The font `SourceSansPro-Bold` is only applied to the selected item. All other items remain in the default font.

**Comment by ittianyu** [comment]
Oh, that is my mistake.
Fix it in 1.1.7.
Thanks for your feedback.
