### ISSUE TITLE
渲染太慢

### ISSUE THREAD

**Issue by wangyuan0217** [ittianyu/BottomNavigationViewEx#191]
![aaa](https://user-images.githubusercontent.com/12730214/89499458-a21ba680-d7f2-11ea-801c-379bf36b5fe6.png)

**Comment by Zvirtuey** [comment]
同感，很耗cpu反应慢

**Comment by BeiHaiCoding** [comment]
大概率是反射导致的

**Comment by BeiHaiCoding** [comment]
会不会是反射导致的
