### ISSUE TITLE
能不能设置没有点击阴影呢

### ISSUE THREAD

**Issue by GTooo** [ittianyu/BottomNavigationViewEx#20]
如题，item项点击都有阴影效果，去掉是否需要修改源码

**Comment by ittianyu** [comment]
应该不需要，点击效果应该是一个 selector，覆盖 item 对应的 selector 就可以了，但是具体是哪个，还得仔细看代码，另外包里把 drawable 都隐藏了，不好找。

**Comment by ittianyu** [comment]
口误，不是隐藏了，是IDE会跳转到 values.xml 中，自己打开包还是能找到，如下，把 v21 中的这个改成和 drawable 包中的一样就行了
`res/drawable-v21/design_bottom_navigation_item_background.xml`

**Comment by GTooo** [comment]
@ittianyu 没事，已经解决了，刚刚看了下，发现有个setItemBackgroundResource方法，这里设置就行了，就是设置了BottomNavigationView背景色，这个item还是能覆盖掉，如果没设置setItemBackgroundResource，所看到的导航栏颜色其实是BottomNavigationView背景色
