### ISSUE TITLE
Why it's Isnt Showing the Menus? Even tho I created the Files Correctly please solve this problem i cant Able to Use it

### ISSUE THREAD

**Issue by a-r-qais** [ittianyu/BottomNavigationViewEx#209]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/66834904/174620854-cf375246-7a57-4af7-af58-a7d048195d4d.png">

**Comment by CListery** [comment]
@Arqais The author of this library has given up maintenance,maybe you can consider using https://github.com/CListery/BottomNavigationEx
