### ISSUE TITLE
Icon and label vanishes/fades a little with animation/shift/itemshift disable

### ISSUE THREAD

**Issue by mumia7575** [ittianyu/BottomNavigationViewEx#24]
Having a bug if I press the buttons fast enough (not slow but not very fast) it vanishes/fades a little of his original color.

Attached Foto of the problem:

![sem titulo](https://cloud.githubusercontent.com/assets/28678442/26029335/b1f04e82-382a-11e7-8290-9e799f1335e4.png)

**Comment by ittianyu** [comment]
I have noticed  the issue. But no idea to resolve it. That is an official issue. My lib is use reflecting to add some methods.

**Comment by mumia7575** [comment]
Ye sorry about that, I already noticed that it's not a bug from your library but from the support library. Opened a ticked on google support: https://issuetracker.google.com/38290403. For anyone that have the same problem star it up 👍 so google notice it.

**Comment by ittianyu** [comment]
Greate !

**Comment by ittianyu** [comment]
Hi, I already know the reason. And do something to make it resolved.
Please try 
```
compile 'com.github.ittianyu:BottomNavigationViewEx:1.2.2'
```

**Comment by jannisveerkamp** [comment]
The issue still exists in the current version of the lib.
