### ISSUE TITLE
Hidden menu item (visibility gone) still takes space in the Bottom Navigation

### ISSUE THREAD

**Issue by umarhussain15** [ittianyu/BottomNavigationViewEx#25]
![image](https://cloud.githubusercontent.com/assets/14268893/26036325/10f75fcc-38f5-11e7-8421-597b11991db5.png)
I have 4 menu items in the bottom navigation but I have set first item's visibility gone. But this is not allowing the remaining 3 icons to take full remaining space. 
Can you suggest a solution for this issue?
How to set effect for the hidden icon like there are only three icons?
My use case is:
having 4 views in view pager, 1st view is not related to the bottom navigation, remaining 3 are selected with the bottom navigation. 
But setting 3 items in navigation, will show the first item as selected but view pager will show the view not related to the selected item.
Thank you.

**Comment by ittianyu** [comment]
Why not just put 3 items in bottom ?
And you need use `setOnNavigationItemSelectedListener` instead of `setUpWithViewPager`. So you could control which pager to show when selected.

**Comment by TheGreat0004** [comment]
@ittianyu  , First thanks for this library, would you please elaborate your answer?

**Comment by ittianyu** [comment]
Oh Sorry, I was misread it. You can pull the last code to see the demo.
![](https://github.com/ittianyu/BottomNavigationViewEx/raw/master/read_me_images/unchecked_first_time.jpg)

**Comment by TheGreat0004** [comment]
Yes, thanks it worked
