### ISSUE TITLE
Allow various features to be defined through XML attributes

### ISSUE THREAD

**Issue by pflammertsma** [ittianyu/BottomNavigationViewEx#26]
It would be nice if the various feature setters such as `setTextVisibility()` or `setLargeTextSize()` could be provided in XML, for instance as `app:textVisibility`.

**Comment by ittianyu** [comment]
I want to do that. While I used reflex. So I want to keep it simple.
And in another hand, using attribute in xml may disturb user's habit. 
So I feel sorry to tell you that I won't add it.

**Comment by pflammertsma** [comment]
I don't know what you mean with disturbing users' habits, but I believe that not supporting XML attributes is a poor design decision. This encourages implementations to manipulate UI components in code, rather than having them defined within the scope of the component and the view. This carries with it other disadvantages as well, such as lack of support for instance states.
