### ISSUE TITLE
Keep all item as unselected by default with Bottom Navigation

### ISSUE THREAD

**Issue by TheGreat0004** [ittianyu/BottomNavigationViewEx#27]
Basically i want to keep all item as unselected or unchecked by default. I had tried a lot unable to do so,

I tried the following link ,

https://stackoverflow.com/questions/41372293/bottomnavigationview-how-to-uncheck-all-menuitems-and-keep-titles-being-displa

but with this solution i got the following opened issue,
https://github.com/ittianyu/BottomNavigationViewEx/issues/25

Any help would be greatly appreciated.

**Comment by ittianyu** [comment]
I have add a demo in StyleActivity just now.  You can take a look.

**Comment by TheGreat0004** [comment]
thanks for the update.
