### ISSUE TITLE
怎么添加对badge的支持？

### ISSUE THREAD

**Issue by kafka0102** [ittianyu/BottomNavigationViewEx#3]
能提供个思路也行，就是一个小红点那种。

**Comment by ittianyu** [comment]
你说的是类似于微信/QQ那样显示动态数量的红圈吧，这个估计得继承类或者重写类，自己绘制，具体方案还得分析官方类的代码。
如果是这种需求，建议用其他第三方库。
目前没能实现该需求，很抱歉。

**Comment by kafka0102** [comment]
多谢回复，官方这个实现和第三方的比较起来实在太粗糙了，只能自己hack或者换种实现了。

**Comment by ittianyu** [comment]
客气了，没有其他疑问我就先关闭问题了。

**Comment by ittianyu** [comment]
新加入了一个badge demo，如有兴趣，欢迎交流。
![](https://github.com/ittianyu/BottomNavigationViewEx/raw/master/read_me_images/view_badger.gif)

**Comment by erichyx** [comment]
@ittianyu 怎么取消红点
