### ISSUE TITLE
建议增加单独Item的setIconVisibility的方法

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [ittianyu/BottomNavigationViewEx#31]
目前的setIconVisibility针对所有BottomNavigationItemView设置。希望能增加类似setIconVisibility（int position ,boolean visibility）的方法控制Item的显示与隐藏.
ps:虽然也可以自己在代码里面获取到BottomNavigationItemView后设置visibility，但是会出现Item宽度间隔不一的问题。

**Comment by ittianyu** [comment]
动态增加或删除 item 比较复杂。设置显示或隐藏也会有间距问题，暂时无法实现。
