### ISSUE TITLE
当ViewPager里添加了多于bottomNavigationView的items数量时，会报index our of bound

### ISSUE THREAD

**Issue by sunzhaoyuan** [ittianyu/BottomNavigationViewEx#33]
您好，当我用自带的BottomNavigationView的时候，我的底部菜单里只有3个items（buttons）， 但是我可以在ViewPager里设置多于3个fragments。例如，我在adapter里添加了五个fragments，而BNV里只有3个items。
但是，当我用BottomNavigationViewEx的时候，会报出index out of bound错误。
请问是否可以添加setItems数量的方法？
抑或您有什么好的解决方案？
多谢

**Comment by ittianyu** [comment]
数量不一样时不要用 setupWithViewPager，自己控制切换，请参照demo https://github.com/ittianyu/BottomNavigationViewEx/blob/master/app/src/main/java/com/ittianyu/bottomnavigationviewexsample/features/viewpager/WithViewPagerActivity.java
