### ISSUE TITLE
快速反复点击切换时，部分文字标题颜色未恢复到正常值。

### ISSUE THREAD

**Issue by evil0angel** [ittianyu/BottomNavigationViewEx#34]
## 感觉像是动画没有执行完导致的
![image](https://user-images.githubusercontent.com/15645708/28200088-7b3ea8a0-689c-11e7-9c4f-43e69c54f587.png)
![image](https://user-images.githubusercontent.com/15645708/28200105-9403886a-689c-11e7-94f5-72fbb59d37ec.png)

**Comment by ittianyu** [comment]
这个bug已经有人报过了，是官方库的问题，我没办法用反射去修复这个问题
建议去给谷歌报bug，在评论列表 +1，希望官方早日修复
https://issuetracker.google.com/issues/38290403

**Comment by ittianyu** [comment]
考虑到可能是动画的问题，简单的处理了一下，我这边测试通过，请尝试一下
`compile 'com.github.ittianyu:BottomNavigationViewEx:1.2.2'`
