### ISSUE TITLE
切换存在BUG

### ISSUE THREAD

**Issue by leeyun** [ittianyu/BottomNavigationViewEx#35]
从0切到3然后切回第0个第2个的文字直接就消失了。

**Comment by ittianyu** [comment]
请参考 [issue34](https://github.com/ittianyu/BottomNavigationViewEx/issues/34)

**Comment by ittianyu** [comment]
考虑到可能是动画的问题，简单的处理了一下，我这边测试通过，请尝试一下
compile 'com.github.ittianyu:BottomNavigationViewEx:1.2.2'
