### ISSUE TITLE
怎么把中间的按钮超出bottomNavigationview的位置显示

### ISSUE THREAD

**Issue by rmtic** [ittianyu/BottomNavigationViewEx#36]
中间按钮，怎么超出边界显示，就是超过BottomView的高度显示

**Comment by ittianyu** [comment]
只用本库做不到，可以考虑把中间那个item 的icon不设置值，文本设置为空字符串，然后做一个 floating action button 定位在底部中间，具体大学和位置请自己调试。

**Comment by rmtic** [comment]
好的，谢谢你

**Comment by ADsuper** [comment]
帅哥，中间按钮的问题解决了没，能否指导一下我

**Comment by ittianyu** [comment]
@ADsuper 晚上我加个 demo

**Comment by ADsuper** [comment]
好的，谢谢

**Comment by ittianyu** [comment]
@ADsuper 已经加了，昨天回去之后有点事给忘了，今晚才想起来。
