### ISSUE TITLE
在NestedScrollView中能不能固定在屏幕底部

### ISSUE THREAD

**Issue by MickeyBadBad** [ittianyu/BottomNavigationViewEx#37]
我的Root View是NestedScrollView，使用BottomNavigationView或Ex都会排到内容底部，不是屏幕底部。layout_gravity 或者 alignParentBottom 都无效～ 
有什么方法固定在屏幕底部么？谢谢。

**Comment by ittianyu** [comment]
ScrollView 里面高度是可变的，做不到固定，你root可以改成 ReleativeLayout ，里面再套 NestedScrollView。
