### ISSUE TITLE
Ripple effect

### ISSUE THREAD

**Issue by amouly** [ittianyu/BottomNavigationViewEx#4]
There is a way to maintain the Ripple Effect after removing the shifting mode?

I'm using this configuration:

```java
bottomNavigationView.enableAnimation(false);
bottomNavigationView.enableShiftingMode(false);
bottomNavigationView.enableItemShiftingMode(false);
bottomNavigationView.setTextVisibility(true);
bottomNavigationView.setIconVisibility(true);
```

I don't want any kind of Shifting but I want to continue having the ripple effect.

Thank you and amazing job!

**Comment by ittianyu** [comment]
Using these api will not cause the ripple effect to disappear. I test in Android 5.0 and it works well.
The ripple effect was supported from Android 5.0. So you can't see it on Android 4.x.
You can see this image.
![](https://github.com/ittianyu/BottomNavigationViewEx/raw/master/read_me_images/no_animation_shifting_mode_item_shifting_mode.gif)

And you just need call these api. The text and icon are visible by default.
```java
bottomNavigationView.enableAnimation(false);
bottomNavigationView.enableShiftingMode(false);
bottomNavigationView.enableItemShiftingMode(false);
```

I'm glad to see someone using my library.

**Comment by amouly** [comment]
@ittianyu the library works fine, it was my issue setting the same color on the background.

Again, thank you for your effort and be sure that this library saved my life 😄 .

**Comment by luneice** [comment]
if you wan to custom the menu item click ripper, you can define style in styles.xml [like this](https://stackoverflow.com/questions/40325422/selected-tabs-color-in-bottom-navigation-view)
so set the BottomNavigationMenuEX theme in xml, it will work!
