### ISSUE TITLE
快速切换文字消失什么时候可以解决呢

### ISSUE THREAD

**Issue by ALguojian** [ittianyu/BottomNavigationViewEx#40]
提个小问题

**Comment by ittianyu** [comment]
现在还有这种情况吗？我已经处理过了，有空等我升级到 SDK 26 看看。

**Comment by ALguojian** [comment]
我看你提交之后，升级1.2.2之后快速切换文字还是会消失

**Comment by ALguojian** [comment]
怎么又回到1.2.1了。老铁

**Comment by ittianyu** [comment]
你说 1.2.2 没作用，而且库升级到 26.0.0 后，里面有个变量找不到了，暂时先回滚。
26.0.0 我暂时没办法使用，是在 谷歌的maven中，挂VPN 也下不下来。我也没办法

**Comment by ALguojian** [comment]
淡淡的忧伤# ~~哈

**Comment by ittianyu** [comment]
请尝试一下 1.2.3
需要更新你的SDK版本到26，并开VPN

**Comment by ittianyu** [comment]
请问 26.0.0 的库有没有这种问题，我先关闭这个 issue了，看了官方代码是做了一些修改，不知道有没有解决，我这连续点了几分钟，没有发现有问题。

**Comment by ALguojian** [comment]
我发现问题还在，并没有解决

**Comment by aesion** [comment]
+1我也遇到这个问题
