### ISSUE TITLE
Have you checked with Android Support v25.4.0?

### ISSUE THREAD

**Issue by kanvuduc** [ittianyu/BottomNavigationViewEx#42]
There are significant changes in Android Support v25.4.0 where some classes are made **internal** :(.

Have you checked?

**Comment by ittianyu** [comment]
Thanks. Let me check.

**Comment by ittianyu** [comment]
Sorry, I  can't download it.

**Comment by ittianyu** [comment]
I use 26.0.0 in version 1.2.3. Please try.

**Comment by kanvuduc** [comment]
Thanks. It works absolutely.
