### ISSUE TITLE
请教，怎么会出现java.lang.NoSuchFieldException: No field mAnimationHelper in class这样的错误？

### ISSUE THREAD

**Issue by 1371030** [ittianyu/BottomNavigationViewEx#46]
09-12 15:06:19.888 20291-20291/? I/zygote: Not late-enabling -Xcheck:jni (already on)
09-12 15:06:19.894 20291-20291/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
09-12 15:06:19.982 20291-20291/com.exectt.app I/InstantRun: starting instant run server: is main process
09-12 15:06:20.068 20291-20291/com.exectt.app W/System.err: java.lang.NoSuchFieldException: No field mAnimationHelper in class Landroid/support/design/internal/BottomNavigationMenuView; (declaration of 'android.support.design.internal.BottomNavigationMenuView' appears in /data/app/com.exectt.app-vrO_uep479VkChTuwsv4Lg==/split_lib_dependencies_apk.apk:classes6.dex)
09-12 15:06:20.068 20291-20291/com.exectt.app W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
09-12 15:06:20.068 20291-20291/com.exectt.app W/System.err:     at com.exectt.app.widgets.BottomNavigationViewEx.getField(BottomNavigationViewEx.java:781)
09-12 15:06:20.068 20291-20291/com.exectt.app W/System.err:     at com.exectt.app.widgets.BottomNavigationViewEx.addAnimationListener(BottomNavigationViewEx.java:109)
09-12 15:06:20.068 20291-20291/com.exectt.app W/System.err:     at com.exectt.app.widgets.BottomNavigationViewEx.init(BottomNavigationViewEx.java:96)
09-12 15:06:20.068 20291-20291/com.exectt.app W/System.err:     at com.exectt.app.widgets.BottomNavigationViewEx.<init>(BottomNavigationViewEx.java:61)
09-12 15:06:20.068 20291-20291/com.exectt.app W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:647)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:418)
09-12 15:06:20.069 20291-20291/com.exectt.app W/System.err:     at android.app.Activity.setContentView(Activity.java:2654)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at com.exectt.app.MainActivity.onCreate(MainActivity.java:41)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at android.app.Activity.performCreate(Activity.java:6975)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at android.os.Looper.loop(Looper.java:164)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-12 15:06:20.070 20291-20291/com.exectt.app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at com.exectt.app.widgets.BottomNavigationViewEx.addAnimationListener(BottomNavigationViewEx.java:110)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at com.exectt.app.widgets.BottomNavigationViewEx.init(BottomNavigationViewEx.java:96)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at com.exectt.app.widgets.BottomNavigationViewEx.<init>(BottomNavigationViewEx.java:61)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:647)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
09-12 15:06:20.071 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:418)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at android.app.Activity.setContentView(Activity.java:2654)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at com.exectt.app.MainActivity.onCreate(MainActivity.java:41)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at android.app.Activity.performCreate(Activity.java:6975)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
09-12 15:06:20.072 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
09-12 15:06:20.073 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-12 15:06:20.073 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
09-12 15:06:20.073 20291-20291/com.exectt.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
09-12 15:06:20.074 20291-20291/com.exectt.app W/System.err:     at android.os.Looper.loop(Looper.java:164)
09-12 15:06:20.074 20291-20291/com.exectt.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
09-12 15:06:20.074 20291-20291/com.exectt.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-12 15:06:20.074 20291-20291/com.exectt.app W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-12 15:06:20.074 20291-20291/com.exectt.app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by ittianyu** [comment]
用的哪个版本
