### ISSUE TITLE
ActivityWithViewPagerBinding where ?

### ISSUE THREAD

**Issue by Paul75** [ittianyu/BottomNavigationViewEx#47]
Hello,

Where is the ActivityWithViewPagerBinding ?

Thanks

**Comment by ittianyu** [comment]
Just download  the project and run. You can see it. And the packages is simple. ViewPager is in features.

**Comment by Paul75** [comment]
I download and found but in line import com.ittianyu.bottomnavigationviewexsample.databinding.ActivityWithViewPagerBinding;

not have the folder databinding ?

**Comment by ittianyu** [comment]
Oh, I use Databinding. You have no need to use it.  You can findviewbyid to get it.

**Comment by Paul75** [comment]
found what ?

**Comment by Paul75** [comment]
and I must declare Fragment ?

Not have an exemple ?

Sorry

**Comment by ittianyu** [comment]
It contains example. If you can not read it. May be you need learn Databinding.
