### ISSUE TITLE
Question: Possible different item icon/color?

### ISSUE THREAD

**Issue by Rainer-Lang** [ittianyu/BottomNavigationViewEx#48]
Sometimes an active item and its inactive state might use different icons, in different shape and different color. Is this possible?

**Comment by ittianyu** [comment]
yeah. you can see it in demo. Have you see it?  In different style.

**Comment by Rainer-Lang** [comment]
Different color - yes, but not other icons.

**Comment by ittianyu** [comment]
![](https://github.com/ittianyu/BottomNavigationViewEx/raw/master/read_me_images/icon_selector_1.jpg)
![](https://github.com/ittianyu/BottomNavigationViewEx/raw/master/read_me_images/icon_selector_2.jpg)

Use selector. It is in demo.

**Comment by Rainer-Lang** [comment]
@ittianyu Thanks. 👍

**Comment by luthfi-leonhart** [comment]
Hi, what if the selected icon in one of the tab has different color than another? I've tried the demo but the icon got tinted.

Edit: fixed by setIconTintList(tabPosition, ColorStateList as null).
