### ISSUE TITLE
底部item的icon如何设置2张渐变的png图

### ISSUE THREAD

**Issue by drowtram** [ittianyu/BottomNavigationViewEx#49]
需求是底部导航栏的icon默认是灰色，选中是橙色渐变的效果，用这个框架后，图片被强制渲染成主题色，怎么解决？或者说，我想两张图片png的来切换选中未选中的icon，不要把我的icon强制再渲染上一层色，该怎么做？

**Comment by ittianyu** [comment]
把这两个属性删掉，就不会改颜色了
```
app:itemIconTint="@color/selector_item_gray_color"
app:itemTextColor="@color/selector_item_gray_color"
```

menu 里面用 selector 实现选中和未选中使用两张图片，请参考 https://github.com/ittianyu/BottomNavigationViewEx/blob/master/app/src/main/res/menu/menu_navigation_selector.xml

渐变好像没办法实现，现在多种状态图片切换一般都是用 selector，如果你能实现就试试吧。

**Comment by drowtram** [comment]
selector切换没有问题，但是我去掉那两个属性，貌似也会给我的icon默认渲染一层colorPrimary这个色值

**Comment by ittianyu** [comment]
那是背景颜色，去掉 backgroundColor 就行

**Comment by drowtram** [comment]
算了，我已经说服UI给把渐变去了，就这样也能满足要求了，😄😄😄

**Comment by Hi-Mike** [comment]
这个没办法实现吧,默认也会着上textColorSecondary

**Comment by Hi-Mike** [comment]
给后来的人看,两张图片在selector中不tinti,设置setItemIconTintList为null就好

**Comment by panyy** [comment]
@Hi-Mike 谢谢
