### ISSUE TITLE
text is not visible along with icon

### ISSUE THREAD

**Issue by reonwaterman** [ittianyu/BottomNavigationViewEx#5]
I have done following coding 

bottomNavigationView.enableAnimation(false);
bottomNavigationView.enableShiftingMode(false);
bottomNavigationView.enableItemShiftingMode(false);

but text is only visible on selected icon. how to show text for all icons.

My android version is 6.0.1 (Mi Note3)

**Comment by ittianyu** [comment]
Have you solve this problem ? I'm sorry I did not get back to you in time.
