### ISSUE TITLE
Vertical center

### ISSUE THREAD

**Issue by estavex** [ittianyu/BottomNavigationViewEx#50]
Vertical center normalization is fucked up. If the navgiation is e.g. 48dp, your icons are 20+dp, they get aligned a bit to the bottom rather than shifted to the top so it can be vertically aligned. Can we have the option to shift the offset of the menu items? OR even better: to let BottomNavigationViewEx do that behind the scenes automatically for us?

**Comment by ittianyu** [comment]
Sorry. There is no way to control shift offest. You can cancel shift mode. Then setting padding yourself.
