### ISSUE TITLE
app:itemIconTint only works for item in state_checked=true for APIs above KitKat

### ISSUE THREAD

**Issue by lidkxx** [ittianyu/BottomNavigationViewEx#51]
Having an issue with **app:itemIconTint**: colors from the xml selector are only applied to items that are in state_checked=true. The ones that are not are not colored. This only happens for APIs ABOVE KitKat.

Here's how I define my BottomNavigationView:

    <com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx
        android:id="@+id/bottomNavView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:background="@android:color/white"
        android:paddingBottom="@dimen/bottom_nav_menu_margin"
        app:elevation="@dimen/bottomview_elevation"
        app:itemIconTint="@@color/bottom_nav_button"
        app:itemTextColor="@color/bottom_nav_button"
        app:layout_constraintBottom_toBottomOf="parent"
        app:menu="@menu/bottombar_menu" />

My selector, that resides in res/color:

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/colorPrimaryDark" android:state_checked="true"/>
    <item android:color="@color/colorPrimaryLight"/>
</selector>
```
I also tried with other possible states, but I learned that [for BottomNavigationView it's indeed state_checked](https://stackoverflow.com/questions/40325422/selected-tabs-color-in-bottom-navigation-view) that we should work with.
I also tried using @drawable instead of @color, and also with 
`<item android:color="@color/colorPrimaryLight" android:state_checked="false"/>` explicitly, but still no luck.
 
Any help appreciated and thank you for your work on this time-saving library!

**Comment by ittianyu** [comment]
Do you try BottomNavigationView  instead of BottomNavigationViewEx?

**Comment by lidkxx** [comment]
OMG, I spent so much time trying to debug it, and it turned out I was editing the layouts for APIs > 21. I have both `layout` and `layout-v21` folders in my `res` directory and I was only editing the first one, hence it would only work for KitKat and below. 

Somehow it seems that I can only see my own mistakes minutes after I submit an issue to your library:) Sorry, and thank you again!
