### ISSUE TITLE
Badge not working

### ISSUE THREAD

**Issue by tdhanjal408** [ittianyu/BottomNavigationViewEx#53]
I am trying to add support for badging in bottom navigation view. As per your examples you used "ActivityBadgeViewBinding" , but this class does not exisit anywhere in library. Pleas help to resolve this.

**Comment by ittianyu** [comment]
Add badge lib
```
compile 'q.rorbin:badgeview:1.1.0'
```


Bind bottom view
```
// add badge
addBadgeAt(2, 1);

private Badge addBadgeAt(int position, int number) {
    // add badge
    return new QBadgeView(this)
            .setBadgeNumber(number)
            .setGravityOffset(12, 2, true)
            .bindTarget(bind.bnve.getBottomNavigationItemView(position))
            .setOnDragStateChangedListener(new Badge.OnDragStateChangedListener() {
                @Override
                public void onDragStateChanged(int dragState, Badge badge, View targetView) {
                    if (Badge.OnDragStateChangedListener.STATE_SUCCEED == dragState)
                        Toast.makeText(BadgeViewActivity.this, R.string.tips_badge_removed, Toast.LENGTH_SHORT).show();
                }
            });
}
```

**Comment by tdhanjal408** [comment]
@ittianyu  Thanks for reply, I did add the same but it gives error at below line

.bindTarget(bind.bnve.getBottomNavigationItemView(position))

Can you please tell me how you getting bind object ?

**Comment by ittianyu** [comment]
Oh, you means `ActivityBadgeViewBinding` ?
That is generate by DataBinding plugin.
You no need use it. Just use findViewById to get `BottomNavigationViewEx`.

**Comment by tdhanjal408** [comment]
Thank you for clarification. It works now!!
