### ISSUE TITLE
BottomNavigationViewEx is shown when keyboard is open

### ISSUE THREAD

**Issue by avelozo** [ittianyu/BottomNavigationViewEx#58]
Hi There!

When I click on a inputText, the keyboard is shown and the  BottomNavigationViewEx is shown above it.
I want to hide it when the keyboard is open.

I have a BottomNavigationViewEx inside my Activity (**RelativeLayout**), my fragment is a **ConstraintLayout**.

I have tried to change the _android:windowSoftInputMode_ in many different ways inside the manifest, I've also tried to change it programmatically  : 

_window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN)_

I've also tried to change my ConstraintLayout to Relative or wrapping it with a Scrollview. Nothing seems to work. :(

Am I missing something? Is it a bug? 

Thanks!!!

**Comment by creativetrendsapps** [comment]
@avelozo I would suggest detecting if the keyboard is open and is at a certain height. Something like this.

void isKeyBoardShowing() {
        try {
            background_color.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                @Override
                public void onGlobalLayout() {
                    Rect r = new Rect();
                    background_color.getWindowVisibleDisplayFrame(r);
                    int screenHeight = background_color.getRootView().getHeight();
                    int keypadHeight = screenHeight - r.bottom;
                    if (keypadHeight > screenHeight * 0.15) {
                       mTabs.setVisibility(View.GONE);
                    } else {
                        mTabs.setVisibility(View.VISIBLE);
                    }

                }
            });

        } catch (Exception ignored) {

        }
    }
