### ISSUE TITLE
change ripple color 

### ISSUE THREAD

**Issue by rajeshvinew** [ittianyu/BottomNavigationViewEx#59]
change ripple color like youtube latest bottom nav red or something

**Comment by ittianyu** [comment]
Add a drawable named `design_bottom_navigation_item_background.xml` and put it into `drawable-v21`.
This is content. You can change the ripple color.
```
<ripple xmlns:android="http://schemas.android.com/apk/res/android"
        android:color="?attr/colorPrimary" />
```
