### ISSUE TITLE
Badger example

### ISSUE THREAD

**Issue by amouly** [ittianyu/BottomNavigationViewEx#6]
Due that the BadgerView used in the example is deprecated, I started looking for an alternative. I found this one:

https://github.com/AlexLiuSheng/BadgeView

I changed a little your example code and apparently it works just fine. Could you give it a try?

Thank you!

**Comment by amouly** [comment]
I changed your example code as follows, with the BadgeView I mentioned below:

```
private BadgeView addBadgeViewAt(int position, String text) {
        // get position
        ImageView icon = bottomNavigationView.getIconAt(position);

        return BadgeFactory.create(this)
                .setTextColor(Color.WHITE)
                .setWidthAndHeight(15, 15)
                .setBadgeBackground(Color.RED)
                .setTextSize(7)
                .setBadgeGravity(Gravity.RIGHT | Gravity.TOP)
                .setBadgeCount(text)
                .setShape(BadgeView.SHAPE_CIRCLE)
                .setMargin(0, 0, 0, 0)
                .bind(icon);
    }
```

It works just fine, but when I select the item with the badge, it makes a weird animation and the NavigationIcon mess up.

**Comment by ittianyu** [comment]
Thank you for you help. I had change the badge lib.

**Comment by amouly** [comment]
Wou! @ittianyu that was fast. Thank you! I'm going to test with your example and let you know!
