### ISSUE TITLE
No way to ignore tinting of pre-colored icons.

### ISSUE THREAD

**Issue by qasimvibrent** [ittianyu/BottomNavigationViewEx#61]
If I have 2 svgs used with selector via state checked and unchecked. I want to be able to keep the color styles of the svgs without having them tinted.
I am not specifying app:itemIconTint yet it is still tinting.
At the moment I see BottomNavigationViewEx forces a tint. 

Anyway to ignore that? @ittianyu

**Comment by ittianyu** [comment]
Try to remove `app:itemIconTint` in xml. I'm not sure.

**Comment by qasimvibrent** [comment]
I did remove the app:itemIconTint, that's the issue/bug. If no tint is specified, why is it tinting ?
