### ISSUE TITLE
BottomNavigationViewEx.mButtons can get out of sync to buttons of underlying BottomNavigationView

### ISSUE THREAD

**Issue by Bombo** [ittianyu/BottomNavigationViewEx#62]
I have my `BottomNavigationViewEx` set up with a `ViewPager` (using `setUpWithViewPager(ViewPager, boolean)`). As the number of `View`s in the `ViewPager` can change at runtime, I'm changing the items in the `BottomNavigationViewEx` accordingly, using `getMenu.removeItem()/.add()` respectively, which seems to be working fine on itself. But afterwards the items in the bottom navigation aren't selected correctly, if an item in between got removed and I'm using the `ViewPager`'s swiping gesture.

So before I got a bottom navigation with `| 0 | 1 | 2 | 3 |` and afterwards it's just `| 0 | 2 |`. Being on `| 2 |` and swiping right to get to `| 0 |` is working fine, but swiping left to select `| 2 |` doesn't get reflected in the bottom navigation.

I think the issue here is in `BottomNavigationViewEx::getBottomNAvigationItemViews()`, as it lazily initializes the internal `mButtons` field only the first time it's accessed and evidently that reference inside `BottomNavigationMenuView` changes due to the `getMenu.removeItem()/.add()` actions.

**Comment by ittianyu** [comment]
No idea. Sorry.
