### ISSUE TITLE
底部导航栏icon

### ISSUE THREAD

**Issue by rcj60560** [ittianyu/BottomNavigationViewEx#63]
@liaolintao  你好请问底部导航栏icon能换成任意我想的设置的icon吗
矢量图并不能满足很多其他的要求 比方我换成一个机器人图标
看到回复
谢谢

**Comment by luongvo** [comment]
@rcj60560 Put your screenshots or demo app url

**Comment by liaolintao** [comment]
@rcj60560 我现在没用这个控件了,不清楚能否使用位图. 
建议你把位图转化为矢量图, 或者直接让UI给你SVG文件, android studio可以将SVG转为矢量图.
UI用设计工具输出SVG文件是非常简单的, 比输出位图还要简单.

**Comment by ittianyu** [comment]
位图支持的，一样的，只要把 menu item 里面的 icon 设置成 drawable 里面的 name 就好。
