### ISSUE TITLE
Problem with setIcon

### ISSUE THREAD

**Issue by ruhy99** [ittianyu/BottomNavigationViewEx#65]
I get the item and I set the icon by using the following method to it: 

```
bottomNavigationViewEx.setIconTintList(4,null);
item.setItem(getDrawable(R.drawable.home));
```

The icon is setting up as normal by the method but then when you change the page or you select another item in the menu it is changed by the android:icon that is set in the menu.xml resource

**Comment by ruhy99** [comment]
Finally I fix it 😫 by using:
```
bottomNavigationViewEx.setIconTintList(4,null);
Menu menu = bottomNavigationView.getMenu();
menu.getItem(4).setIcon(R.drawable.home);
```
and not:
bottomNavigationViewEx.setIconTintList(4,null);
MenuView.ItemView item = bottomNavigationView.getBottomNavigationItemView(4);
item.setIcon(R.drawable.home);

**Comment by roarapps** [comment]
Thanks so much!!! This helped me after 2 days of researching
