### ISSUE TITLE
How to copy BottomNavigationViewEx.java  to my project?

### ISSUE THREAD

**Issue by WenzhuoHao** [ittianyu/BottomNavigationViewEx#67]
Do I need to create a new package named "com.ittianyu.bottomnavigationviewex"?
Where should I put the BottomNavigationViewEx.java .java file?

Thank you very much.

**Comment by ittianyu** [comment]
No.

**Comment by WenzhuoHao** [comment]
您回复的真快。所以我应该怎么用BottomNavigationViewEx.java？

**Comment by ittianyu** [comment]
复制到你项目里，当个普通 view 类用

**Comment by WenzhuoHao** [comment]
复制到项目的哪个地方？我是新手，不太会，是在抱歉，我现在把您写的view加到了xml里，能够现实，但是在main activity里写BottomNavigationViewEx 就说找不到

**Comment by ittianyu** [comment]
复制到任意包名下，就是一个java 文件，和你自己写的一样。放到 xml 里面的时候，要把包名改成类所在那个包名。

**Comment by WenzhuoHao** [comment]
那这个java文件里的package名也得改成我自己的package名吧？

**Comment by WenzhuoHao** [comment]
已经按您教我的做法做了，但是有个问题是这个java文件里有报错，在两个方法上，button.getItemPosition()  mMenuView.updateMenuView(); 提示的是ButtonNavigationView.updateMenuView can only be called from within the same library group

**Comment by ittianyu** [comment]
正常，忽视就好，没影响

**Comment by WenzhuoHao** [comment]
十分感谢，已经可以了，再次感谢，虽不知你那里的时间，但是我在国内，祝您晚安~
