### ISSUE TITLE
How many items can we add in a bottomNavigationView

### ISSUE THREAD

**Issue by SimonPeter1909** [ittianyu/BottomNavigationViewEx#69]
I was using your dependency, Its great... There is no problem till 5 items.... when I add the 6th item in the menu it throws an error...

` java.lang.RuntimeException: Unable to start activity ComponentInfo{trickandroid.cablevasul/trickandroid.cablevasul.ActivityCustomerList.CustomerListActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx`

**Comment by ittianyu** [comment]
Don't support more than 5.
