### ISSUE TITLE
如何使用png图片而不是svg

### ISSUE THREAD

**Issue by hansionit** [ittianyu/BottomNavigationViewEx#70]
我想在一个选项卡上，选中和非选中用两张多彩的icon进行切换。但实际使用时，会被更改为单一颜色，如何让png或svg能将其原本的多彩颜色显示出来

**Comment by xiaolongwuhpu** [comment]
@hansionit 你好, 这个是如何设置的?
我也想每个icon都使用两个选中和为选的两个图片代替,
