### ISSUE TITLE
Badge not able to reset with 0

### ISSUE THREAD

**Issue by tdhanjal408** [ittianyu/BottomNavigationViewEx#71]
I am facing issue with badge in this library. For example if Initially number is 0 in below line of code and then number is 30 , it works. But If try to reset this number again back to 0 it does not work and still shows 30 on badge.Please help.

new QBadgeView(context)
                .setBadgeNumber(number)
                .setGravityOffset(12, 2, true)
                .bindTarget(bottomNavigationViewEx.getBottomNavigationItemView(position));

**Comment by tdhanjal408** [comment]
I was able to resolve it. I was not holding previous object instance.

**Comment by mushfiq36** [comment]
I faced the same issue. @tdhanjal408 Can you please provide the code snippet what actually you did to solve it?

**Comment by mob-rockstar** [comment]
// Badge View
       QBadgeView badgeView = null;

       private Badge addBadgeAt(int position, int number) {
        // add badge
        if (badgeView == null){
            badgeView = new QBadgeView(this);
        }

        badgeView.setBadgeNumber(number)
                .setGravityOffset(15, 2, true)
                .bindTarget(bottomBar.getBottomNavigationItemView(position))
                .setOnDragStateChangedListener(new Badge.OnDragStateChangedListener() {
                    @Override
                    public void onDragStateChanged(int dragState, Badge badge, View targetView) {
                        if (Badge.OnDragStateChangedListener.STATE_SUCCEED == dragState)
                            Log.d(TAG, "badge removed");
                    }
                });

        return badgeView;
       }

     // Set the badge number
     addBadgeAt(2, 0);

**Comment by mushfiq36** [comment]
@mob-rockstar Thanks for the code snippet. It was resolved anyway.
