### ISSUE TITLE
add item text at bottom of icon

### ISSUE THREAD

**Issue by mehdi-amirafshar** [ittianyu/BottomNavigationViewEx#72]
Hi,
How can I add item text at bottom of icon ?
I mean before I click and select an item

**Comment by bhuyiaelectronics** [comment]
Bhuyia electronics now available website Email Host

**Comment by bhuyiaelectronics** [comment]
Thank you bhuyia electronics and communication skills both written for your email address

**Comment by ittianyu** [comment]
Not clear. You can see the demo. That is most I can do.
