### ISSUE TITLE
底部凸起bug

### ISSUE THREAD

**Issue by duyb** [ittianyu/BottomNavigationViewEx#73]
FloatingActionButton换成其它控件（如imagView）时，不能正常展示，被BottomNavigationViewEx遮盖了布局；FloatingActionButton的app:elevation设置成小于8dp时，布局也被遮盖。

**Comment by itsJoKr** [comment]
这不是一个错误，这是一个功能。

**Comment by loperSeven** [comment]
你需要保证ImagView在BottomNavigationViewEx之上哟

**Comment by helloworld10010** [comment]
我也蒙了，这什么原理。 明明它在BottomNavigationViewEx后边，竟然被挡住，用elevation属性才显示
