### ISSUE TITLE
Bottom Navigation View padding

### ISSUE THREAD

**Issue by jeffersonlicet** [ittianyu/BottomNavigationViewEx#8]
How can i set the View padding top and bottom using setTextVisibility(false);? The bar height is so small. Thank you.

**Comment by jeffersonlicet** [comment]
Found this solution:
Instead of declare padding in layout i created a new style. Thank you.
` <style name="bnve">
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:paddingTop">7dp</item>
        <item name="android:paddingBottom">7dp</item>
        <item name="android:background">@color/white</item>
    </style>
    `

**Comment by ittianyu** [comment]
Thanks for your feedback !
