### ISSUE TITLE
icon切换

### ISSUE THREAD

**Issue by duwurensheng010** [ittianyu/BottomNavigationViewEx#84]
icon选中切换只能通过app:itemIconTint属性设置吗，可不可以用selector自己去切换icon

**Comment by loperSeven** [comment]
可以的，将itemIconTint设置为空，代码中为bottomNavigationView.setItemIconTintList(null);，然后在menu菜单中的item项配置其icon为selector即可

**Comment by duwurensheng010** [comment]
我试了，icon切换不起作用，两个状态的图标都不显示，切换的时候只是一个色块在变。

**Comment by loperSeven** [comment]
你是在xml内设置的itemIconTint吗
下面是我的实现方式
menu菜单配置
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:id="@+id/i_home"
        android:checked="true"
        android:icon="@drawable/selector_main_home"
        android:title="首页" />

    <item
        android:id="@+id/i_order"
        android:icon="@drawable/selector_main_order"
        android:title="订单" />

    <item
        android:id="@+id/i_setting"
        android:icon="@drawable/selector_main_my"
        android:title="设置" />
</menu>
xml内
 <com.loper7.base.widget.BottomNavigationViewEx
        android:id="@+id/main_bottomNavigationView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        app:itemTextColor="@drawable/selector_item_account_color"
        android:background="@color/colorWhite"
        app:menu="@menu/menu_navigation" />
java代码内
        //底部导航栏配置
        bottomNavigationView.setItemIconTintList(null);
        bottomNavigationView.enableItemShiftingMode(false);
        bottomNavigationView.enableShiftingMode(false);
        bottomNavigationView.enableAnimation(false);
        bottomNavigationView.setIconSize(20, 20);
        bottomNavigationView.setItemHeight(BottomNavigationViewEx.dp2px(this, 52));
        bottomNavigationView.setIconsMarginTop(BottomNavigationViewEx.dp2px(this, 10));

**Comment by loperSeven** [comment]
下面是我的代码实现，你可以参照一下，看是否可以解决
``` Java

    <com.loper7.base.widget.BottomNavigationViewEx
        android:id="@+id/main_bottomNavigationView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        app:itemTextColor="@drawable/selector_item_account_color"
        android:background="@color/colorWhite"
        app:menu="@menu/menu_navigation" />
```
``` Java
  //底部导航栏配置
        bottomNavigationView.setItemIconTintList(null);
        bottomNavigationView.enableItemShiftingMode(false);
        bottomNavigationView.enableShiftingMode(false);
        bottomNavigationView.enableAnimation(false);
        bottomNavigationView.setIconSize(20, 20);
        bottomNavigationView.setItemHeight(BottomNavigationViewEx.dp2px(this, 52));
        bottomNavigationView.setIconsMarginTop(BottomNavigationViewEx.dp2px(this, 10));
```

**Comment by loperSeven** [comment]
xml内的itemIconTint不支持设置null ，所以只能在代码内设置setItemIconTintList(null);

**Comment by loperSeven** [comment]
app:itemTextColor 是设置字体选中颜色的，不支持使用drawable/mipmap图片
 要设置菜单图片的选中图片变化可以在app:menu="@menu/menu_navigation"中给单独的menu项设置selector，这个是支持drawable/mipmap图片的
