### ISSUE TITLE
Failed to resolve: com.github.ittianyu:BottomNavigationViewEx:1.2.4 Show in File Show in Project Structure dialog

### ISSUE THREAD

**Issue by Ouissalb** [ittianyu/BottomNavigationViewEx#85]

**Comment by icarapovic** [comment]
Apply this fix: https://stackoverflow.com/a/41529064/1090523

**Comment by Ouissalb** [comment]
I already did that but I still got the same error

**Comment by icarapovic** [comment]
Then it must be something else/specific to you, I had this error and it went away by rearranging repositories like mentioned in my previous comment.
