### ISSUE TITLE
1. Caused by: java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by WinnerLi** [ittianyu/BottomNavigationViewEx#86]

**Comment by WinnerLi** [comment]
在demo中使用了BottomNavigationViewEx，正式签名之后在荣耀9运行，直接报错，但是在Android P版本和小米6测试是没问题的。
![image](https://user-images.githubusercontent.com/18546315/40900722-848544f6-67ff-11e8-9918-186964a1069e.png)

**Comment by ittianyu** [comment]
可以试试 2.0.0 版本
