### ISSUE TITLE
Exclude android:label attr from Android Manifest

### ISSUE THREAD

**Issue by bogdanzurac** [ittianyu/BottomNavigationViewEx#9]
Cannot use library since it uses the label attr in its own Android Manifest.

Error:Execution failed for task ':mobile:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/title_app) from AndroidManifest.xml:18:13-46
  	is also present at [com.github.ittianyu:BottomNavigationViewEx:1.1.2] AndroidManifest.xml:13:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:7:5-58:19 to override.

**Comment by ittianyu** [comment]
You could try to rename title_app to app_name.

**Comment by bogdanzurac** [comment]
Yes, but this is just a temporary fix. The attribute android:label being present in both packages is the problem, not the actual name of the label value.

Also worth noting is that the gradle plugin 2.3.0-rc1 fixes the issue by providing the tools:replace="android:label" attr, which is yet another rather temporary fix.

I would suggest removing the label altogether from the library, since it isn't needed, as it is not a user-facing string. It's not an urgent matter, but would be nice to have in a future release.

**Comment by ittianyu** [comment]
Ok, I will remove it at next release. Thank you for your feedback.

**Comment by ittianyu** [comment]
Already update. And add some new styles.
