### ISSUE TITLE
Where do I put the .jar? 

### ISSUE THREAD

**Issue by juliandik** [ittianyu/BottomNavigationViewEx#90]
Hey I'm trying your tweaked bottomnavigationview but I wonder where to put the .jar u have in your installation. I get this error: 
![image](https://user-images.githubusercontent.com/22636158/41149080-e76683ba-6b0a-11e8-9fd5-0c8a710df2c0.png)

Thank you alot.

**Comment by Mistic92** [comment]
It looks like you have a problem with dex and need to use multidex https://developer.android.com/studio/build/multidex

**Comment by ittianyu** [comment]
You can copy the java file.
Or use gradle to download.
