### ISSUE TITLE
升级到api28后，mMenuView = getBottomNavigationMenuView() 返回为空

### ISSUE THREAD

**Issue by jhyc** [ittianyu/BottomNavigationViewEx#92]
升级到api28后，mMenuView = getBottomNavigationMenuView() 返回为空

**Comment by souta0104** [comment]
**I have a similar problem.**
The getField () method always returns null.

**Comment by jcsla** [comment]
@jhyc @souta0104 
check out this pull requests.

https://github.com/ittianyu/BottomNavigationViewEx/pull/96

**Comment by TONKIA** [comment]
the same problem

**Comment by ittianyu** [comment]
I am sorry to be late. Please use version 2.0.0 if support lib >= 28.
For AndroidX, please add config into `gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```
